function  sameLaneList = getSameLaneList(vNo,edgeNos,laneIdxDevs,opsStates,latWidth)   %#codegen
    sameLaneList = find(edgeNos == edgeNos(vNo) & ...
        laneIdxDevs >= (laneIdxDevs(vNo) - latWidth) & ...
        laneIdxDevs <= (laneIdxDevs(vNo) + latWidth) & opsStates); % 这里是本条车道的所有车未停止的车
end